# Generated by Django 2.2.19 on 2023-06-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=10)),
                ('gene_strand', models.CharField(max_length=10)),
                ('gene_location', models.CharField(blank=True, max_length=50)),
                ('gene_id', models.CharField(max_length=50)),
                ('gene_name', models.CharField(max_length=100)),
                ('gene_alias', models.CharField(max_length=100)),
                ('gene_fullname', models.CharField(max_length=100)),
                ('gene_seq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=50)),
                ('transcript_location', models.CharField(max_length=50)),
                ('transcript_seq', models.TextField()),
                ('total_cds_seq', models.TextField()),
                ('protein_seq', models.TextField()),
                ('upstream_3k_location', models.TextField()),
                ('upstream_3k_seq', models.TextField()),
                ('five_prime_UTR_locations', models.TextField()),
                ('five_prime_UTR_seqs', models.TextField()),
                ('cds_locations', models.TextField()),
                ('cds_seqs', models.TextField()),
                ('intron_locations', models.TextField()),
                ('intron_seqs', models.TextField()),
                ('three_prime_UTR_locations', models.TextField()),
                ('three_prime_UTR_seqs', models.TextField()),
                ('downstream_3k_location', models.TextField()),
                ('downstream_3k_seq', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPBWidgets.Gene')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPBWidgets.Species'),
        ),
        migrations.CreateModel(
            name='BlastDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=100)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPBWidgets.Species')),
            ],
        ),
    ]
